name: Publish to pub.dev

on:
  workflow_run:
    workflows: ["Create Tag from pubspec.yaml"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1